name: "Build and Push Docker Container"
on:
    push:
        branches: [main]

env:
  ACR_REGISTRY: myregistrye36f2c4c.azurecr.io
  IMAGE_NAME: naca-airfoil-pipeline
  IMAGE_TAG: latest

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: read
        
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
                
            - name: Log in to Azure Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.ACR_REGISTRY }}
                  username: ${{ secrets.AZURE_CLIENT_ID }}
                  password: ${{ secrets.AZURE_CLIENT_SECRET }}


            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                context: .
                push: true
                tags: ${{ env.ACR_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
                cache-from: type=gha
                cache-to: type=gha,mode=max